"""Add translations table

Revision ID: 47be92b7dba4
Revises: 5708243efd59
Create Date: 2026-03-23 02:02:35.405496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47be92b7dba4'
down_revision: Union[str, Sequence[str], None] = '5708243efd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('brand_raw', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('body_type_raw', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('color_raw', sa.String(), nullable=True))
    op.add_column('cars', sa.Column('transmission_raw', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'transmission_raw')
    op.drop_column('cars', 'color_raw')
    op.drop_column('cars', 'body_type_raw')
    op.drop_column('cars', 'brand_raw')
    # ### end Alembic commands ###
