"""update Car model

Revision ID: 5708243efd59
Revises: 9b26565c9f58
Create Date: 2026-03-23 00:14:09.959624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5708243efd59'
down_revision: Union[str, Sequence[str], None] = '9b26565c9f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
