"""Add total_price to Car model

Revision ID: 82da18b72fbb
Revises: 900d2c60d5f9
Create Date: 2026-03-23 02:54:24.759592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82da18b72fbb'
down_revision: Union[str, Sequence[str], None] = '900d2c60d5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('total_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'total_price')
    # ### end Alembic commands ###
