"""Add translations table

Revision ID: 900d2c60d5f9
Revises: 47be92b7dba4
Create Date: 2026-03-23 02:12:06.360015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900d2c60d5f9'
down_revision: Union[str, Sequence[str], None] = '47be92b7dba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('original', sa.String(), nullable=False),
    sa.Column('translated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('type', 'original')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###
