"""create cars table

Revision ID: be201adf9309
Revises: 
Create Date: 2026-03-22 01:06:38.747605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be201adf9309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    #car_properties
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('vehicle_price', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('inspection', sa.String(), nullable=True),
    sa.Column('repair_history', sa.String(), nullable=True),
    sa.Column('warranty', sa.String(), nullable=True),
    sa.Column('maintenance', sa.String(), nullable=True),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('is_new_like', sa.Boolean(), nullable=True),
    sa.Column('non_smoker', sa.Boolean(), nullable=True),
    sa.Column('damaged', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
